### ISSUE TITLE
Vehicle selected by sales person is not reflected on the underwriter's screen

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#33]
Example:  I logged in as a salesperson (los.salesperson@waterwheeldata.com - associated with Walt Lazar) and worked application #34.  I picked the vehicle as stock #: P756AV and submitted the application to underwriting.

I logged in as a underwriter (sraghun@waterwheeldata.com) and pulled up application 34.  I see the vehicle is still listed as 7T810AV.

**Comment by bbuchanan** [comment]
Right now there isn't any way to notify the UI that the application has changed. It loads the apps on startup and there is no explicit reload. For the time being, I've added a reload trigger to the recent deals screen so that they'll get the latest when they go there. If you want it a different way, feel free to reopen this.
