### ISSUE TITLE
Missing Fields in application

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#35]
Under Basic Information: 
Marrital Status (field missing in application)
Number of Dependents (missing value)
Age of Dependents (missing in application)

Under Address:
missing county
missing township
missing years at the address
missing months at address
missing mortgage or rent per month

Current Employer: 
missing hourly pay
missing hourly amount

Under Income and Debt - fields not populating (may not be included in API?)
missing merchandise vs. vehicle selection
missing chapter 7,11,13

Missing Block for Previous Employment: 
![image](https://user-images.githubusercontent.com/59945434/73099426-7faae700-3eb9-11ea-806b-baa69d467ee5.png)

**Comment by bbuchanan** [comment]
I'm confused, the mockflow doesn't have these fields. Which one is right? Where are you getting these additional fields?

Also, we agreed that the age of dependents was goofy because it's a number, yet it's only one field, so it doesn't really make sense ... unless you guys want to store it as a string and parse it (seems silly too).

Also, if there are previous employments, they'll show as a list ... current employment is the first one. If that's not functioning, open a different issue.

**Comment by bbuchanan** [comment]
Number of Dependents is missing because they misspelled it. I changed our code to be misspelled as well, so we should start picking up this field after the next deploy.

**Comment by humike** [comment]
I've added the following fields to the mock flow.

County and Rent Per Month on the info tab

Hourly Rate and Number of hours worked on the employment tab

**Comment by bbuchanan** [comment]
I've added everything under basic information except for Age of Dependents. We've decided not to include that.

I've added everything under "Address"

I've added everything under "Employer"

I've added everything under Income & Debt, but I realized that bankruptcy chapter was not being set from the data feed. That has since been corrected, but we'll need new apps to see it work.
