### ISSUE TITLE
Clicking on the pencil to open the app some times doesn't work

### ISSUE THREAD

**Issue by sraghun** [bbuchanan/los-issues#63]
It some times takes 2 or 3 clicks to open an app.  This seems to happen in both Chrome and Safari.  Mike also reported the same thing on Chrome.

**Comment by humike** [comment]
Happening now in Firefox, too

**Comment by bbuchanan** [comment]
I've seen this happen once or twice immediately upon load. I changed some things in the routing and then tried in Firefox, Chrome and Safari and could no longer make it happen. Since I couldn't reliably reproduce it, I'm not 100% confident it's fixed. But maybe 90% sure.

Please reopen if you see this again and tell me what stage you were in (just loading the web app, came out of another app and tried to open a new app, etc).

Will deploy this later today with the other fixes made since the demo call this afternoon.
