### ISSUE TITLE
Workflow after conditional approval?

### ISSUE THREAD

**Issue by humike** [bbuchanan/los-issues#92]
So after the loan goes to conditional, I can't seem to move it to the approval or deny stage. 
What is the workflow to move the application from conditional approval to the UW and setting it to approve or deny?

**Comment by humike** [comment]
![image](https://user-images.githubusercontent.com/59945434/74278151-bfaa0080-4ce6-11ea-8124-2ae33d03b874.png)

**Comment by humike** [comment]
The flow needs to work like this.

The conditional approval needs to go back to the salesperson.
Salesperson reviews the notes, makes the appropriate changes, hits submit again, thus sending it back to the underwriter.
Then UW can reapprove, conditionally approve, or deny the deal.

**Comment by bbuchanan** [comment]
heya Mike, have a look at this issue. I think it mostly says what you say, however, one big difference. It seems to matter if a salesperson or underwriter is making the status change. Can you think of why it would matter if a salesperson or underwriter modifies it?

https://github.com/bbuchanan/los-issues/issues/75

**Comment by bbuchanan** [comment]
I found the bug in implementing issue #75 and that has been addressed. I was basically updating a copy of the application status, not the one actually being saved to the database, but I still don't think that makes it behave as you're outlining.

And you're right, you cannot change the application status via the dropdown. I believe this is by design since this can circumvent the workflow.

I've deployed my latest changes to the server. Please try again. If it doesn't work to your liking, lets have another quick call.

**Comment by humike** [comment]
yep, looks like it's working correctly now.
